FROM node:20.12.0-alpine3.19
# Set build arguments
ARG DATABASE_URL

# Set environment variables
ENV DATABASE_URL=${DATABASE_URL}
WORKDIR /usr/src/app
COPY package.json  package-lock.json turbo.json ./
COPY apps ./apps
COPY packages ./packages
RUN npm install
RUN npm run db:generate
RUN npm run build:user-app
EXPOSE 3000
CMD ["npm", "run", "start-user-app"]